### ISSUE TITLE
Don't parse notebook file

### ISSUE THREAD

**Issue by hadim** [mkdocstrings/autorefs#21]
I am using the latest version.

I use the `mkdocs-jupyter` plugin so I have some `ipynb` files in my `nav`:

```yaml
nav:
  - Examples:
      - dsdasda: examples/xxx.ipynb
      - dsdsd: examples/xxx.ipynb
      - dasdasd: examples/xxx.ipynb
```

It looks like `mkdostrings` try to parse those files because I have plenty of the following warnings:

```bash
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[C]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[C]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[O]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[readonly]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[readonly]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[readonly]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[C]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[C]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[O]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[=C]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[=C]' 
WARNING -  mkdocstrings.plugin: examples/dsdsdsd.ipynb: Could not find cross-reference target '[=C]' 
````

Would that be possible to add an option to ignore those files? (it also slows down the doc building process because usually, those notebook files are quite large (JSON based).

## Boost priority

- Boost priority in our backlog through [Polar.sh](https://polar.sh/pawamoy). Higher pledge, higher priority.
- Minimum pledge by user/organization is $5, minimum amount for boost is $30. 
- View [all issues with pledges](https://polar.sh/pawamoy/issues?sort=most_funded&badged=1).
- We receive the funds once the issue is completed and confirmed by you.
- Features with the [insiders](../labels/insiders) label are released to sponsors first, and tied to a [funding goal](https://pawamoy.github.io/insiders/#funding).

<a href="https://polar.sh/mkdocstrings/autorefs/issues/21">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/mkdocstrings/autorefs/issues/21/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/mkdocstrings/autorefs/issues/21/pledge.svg">
</picture>
</a>

**Comment by bswck** [comment]
Can't reproduce. Maybe fixed by mkdocs-jupyter upstream? Please lmk about repro steps if you still encounter this.

**Comment by pawamoy** [comment]
I'll close as per @bswck's investigation and comment. We'll reopen if the initial issue is updated 🙂
