### ISSUE TITLE
Links not created when text breaks line

### ISSUE THREAD

**Issue by cz4rny** [mkdocstrings/autorefs#31]
In short, when link title has a line break, linking doesn't work:

```markdown
See [ArgoCD diagram doesn't reflect my
manifests][argocd-diagram-doesnt-reflect-my-manifests].
```

while the same text but in a single line does:

```markdown
See [ArgoCD diagram doesn't reflect my manifests][argocd-diagram-doesnt-reflect-my-manifests].
```

**Comment by oprypin** [comment]
I confirm this! Vanilla Markdown references support this and autorefs doesn't. Will send out a PR now
