### ISSUE TITLE
Add a warning if a heading title is used in multiple places

### ISSUE THREAD

**Issue by samvanstroud** [mkdocstrings/autorefs#35]
This should cause `mkdocs build -s` to fail.

**Comment by pawamoy** [comment]
Hi @samvanstroud, we just merged #39, which allows to define unique aliases pointing to specific headings. I believe this solves the issue described here (headings appearing in multiple places): since we can now define unique aliases, duplicated headings pose no issue and shouldn't emit warnings.

**Comment by samvanstroud** [comment]
Hi @pawamoy, thanks for the feature! This is great.

What happens if aliases are not defined but multiple headings exist? i.e. in the case that the user either 1) doesn't know that a title is being multiply defined or 2) doesn't know about this feature. In that case I think a warning should still be emitted.

**Comment by beilm** [comment]
I had the same problem and made a PR. Maybe that will help here too? 
https://github.com/mkdocstrings/autorefs/pull/50

**Comment by pawamoy** [comment]
Thanks again @beilm!
