### ISSUE TITLE
[Question/Feature Request] Relative references

### ISSUE THREAD

**Issue by lmmx** [mkdocstrings/autorefs#36]
I can write autorefs like this:

```py
"""
See:
[link text][my_pkg.subpkg.main.myfuncdef]
"""
from .subpkg.main import myfuncdef
```

Would it be possible in any way to make this "relative"? e.g.

```py
"""
See
[link text][.subpkg.main.myfuncdef]
"""
from .subpkg.main import myfuncdef
```

This would make it more concise to document nested subpackage/submodule structures (with apologies if this is an existing feature I've missed in your docs)

**Comment by pawamoy** [comment]
Hello, thanks for the request.

This has been asked previously, but more specifically for the Python handler. A user actually implemented their own handler, based on the official one, to support this, see https://github.com/analog-garage/mkdocstrings-python-xref.
I rejected the offer to merge it upstream because the implementation and proposed syntax seemed too complex to my taste.

But I still want to implement this, particularly in a generic way, through autorefs :+1: See previous conversation here: https://github.com/mkdocstrings/python/pull/28

**Comment by lmmx** [comment]
I can see what you mean! Simplicity is key. It's probably wise to sync up on a plan before beginning writing.

The overall computation being proposed here seems simple so this should be achievable (and low maintenance).

We want to designate symbols according to the level of their definition in the source code.

I was proposing to just mimic the import statement syntax, and having read #28 I feel it best to introduce no new special characters. A DSL should be self-explanatory for ease of use and I couldn't glance at that and feel confident how to write it.

If it's good enough for the import machinery it should be good enough for mkdocstrings!

I like your [point](https://github.com/mkdocstrings/python/pull/28#issuecomment-1354654984) that there should be one canonical way of writing a reference.

The one question seems to be which way to root a reference we would choose.

To take the example of:

- a package `my_pkg`,
  - containing a module `my_mod`
    - containing a class `MyCls`
      - containing a method `my_method`

We write its full dotted module path as:

```py
my_pkg.my_mod.MyCls.my_method
```

> [!TIP]
>
>  This "full dotted module path" = the dotted import path `my_pkg.my_mod` joined by a `.` onto its "qualname" (a.k.a. "[qualified name](https://stackoverflow.com/questions/58108488/what-is-qualname-in-python)") `MyCls.my_method`

In the `my_method()` docstring, the 2 ways to consider the 'root' of a reference `..` are:

1) Rooted top-down, from the module [implicitly] at the start of a qualname, like imports
  - **Pro:** more Pythonic because it retains the meaning of the import dotted syntax
  - **Meaning:**
    - `.` would refer to `my_mod` (thus `.MyCls` refers to the class)
    - `..` would refer to `my_pkg`

```py
# my_pkg/my_mod.py
class MyCls:
    """I am [`MyCls`][.MyCls] and I contain [`my_method()`][.MyCls.my_method]"""
    def my_method(self):
        """I am [`my_method`][`.MyCls.my_method`] and I am in [`MyCls`][.MyCls]"""
```

2) Rooted bottom-up, from the object at the end of a qualname
  - **Pro:** more concise for references within a parent object
  - **Meaning:**
    - `.` would refer to `my_method`
    - `..` would refer to `MyCls`

```py
# my_pkg/my_mod.py
class MyCls:
    """I am [`MyCls`][.] and I contain [`my_method`][.my_method]"""
    def my_method(self):
        """I am [`my_method`][.] and I am in [`MyCls`][..]"""
```

Looking at #28 it seems that the bottom-up root was chosen, and this was not in itself problematic (only that other things were introduced).

It's probably undesirable to change that decision.

Your [testing](https://github.com/mkdocstrings/python/pull/28#issuecomment-1354654984) also landed on that as the more concise (I can see that at a glance too: writing it out with the source code demo here its superiority is even clearer).

I actually don't have much more to add here, seems nice and simple at that!

**Comment by lmmx** [comment]
I guess I should take my issue over there then :-) Sorry I only just noticed that after writing that brief out above :sweat_smile: I will close this issue and quote the above in a new issue there.
