### ISSUE TITLE
feature: Catch [`pathlib.Path()`][] in the same way as [`pathlib.Path`][]

### ISSUE THREAD

**Issue by bswck** [mkdocstrings/autorefs#49]
Caveats:
- Should we make sure these refs are actually callable? I'd rely on the developer here.
- How does that relate to other languages? What about `std::string{}` in C++ if we're about to support it in the future?

**Comment by bswck** [comment]
Lovely discrepancies in Markdown rendering. Eh.

**Comment by bswck** [comment]
The main motivation behind this was that when I was writing slothy docs I wanted to cross-ref built-in `globals()` and `locals()`.

A natural idea was ``[`globals()`][]``, akin to ``[`globals`][]``, so that I wouldn't need to write ``[`globals()`][globals]``.

**Comment by pawamoy** [comment]
Hey @bswck, thanks for the request!

> Should we make sure these refs are actually callable? I'd rely on the developer here.

Definitely not! That's out of scope for autorefs :slightly_smiling_face: So yes, expect developers to do the right thing.

> How does that relate to other languages? What about std::string{} in C++ if we're about to support it in the future?

That would have been my main point if you didn't already raise it. The use of parentheses, although very common, is specific to a given language. autorefs must stay language-agnostic, so unless we find a way to delegate parsing of identifiers to mkdocstrings handlers, we won't support this. Note that there's work going in this direction (some delegation to handlers), but it's too soon to speak about it here :slightly_smiling_face:

**Comment by bswck** [comment]
Thanks. I'm closing this in favor of a feature proposal that respects the language-agnostic nature of autorefs.
