### ISSUE TITLE
docs: Gitter links appear broken on PyPI and GitHub

### ISSUE THREAD

**Issue by pushfoo** [mkdocstrings/autorefs#53]
### Is something unclear, missing or outdated in our documentation?
1. Go to PyPI or the README.md
2. Click the Gitter link
3. Observe the following:
![image](https://github.com/user-attachments/assets/ae0b065d-0ef5-4391-82be-a82fd366ed08)

**Comment by pawamoy** [comment]
Thanks! This is now fixed (the room didn't exist, I created one and updated the link). The link on PyPI will be updated with the next release.
