### ISSUE TITLE
change: Make failed cross-reference lookup in docstrings clearer

### ISSUE THREAD

**Issue by pushfoo** [mkdocstrings/autorefs#54]
### Is your change request related to a problem? Please describe.

When I had a typo in a docstring, the output reported the error as in the markdown file rather than the docstring:
```
WARNING -  mkdocs_autorefs: api/annotations.md: Could not find cross-reference target
           '[package.oop.annotations]'
```

### Describe the solution you'd like
More detailed / accurate error output which includes:
1. The docstring file
2. The item the docstring is on
3. Docstring line number
4. Ideally, accurate file line number

### Describe alternatives you've considered
N/A?

### Additional context

I have:
1. A `package.annotations` submodule
2. A `docs/api/annotations` file using mkdautodocs (`# ::: package.annotations`)

The typo was in the `package/annotations.py` file

**Comment by pawamoy** [comment]
Thanks for the change request :slightly_smiling_face: It makes a lot of sense, and this is something I've wanted to improve indeed. PR #46 is a first step to make this possible :smile: I'll report progress here :slightly_smiling_face:

**Comment by pawamoy** [comment]
PR #46 updated to add more context around error, and merged. Expect a release soon :slightly_smiling_face:

**Comment by pushfoo** [comment]
Just saw this, ty!
