### ISSUE TITLE
Missing identifier with Markdown in the name gets weirdly transformed

### ISSUE THREAD

**Issue by oprypin** [mkdocstrings/autorefs#6]
Given the input `[*Foo-bar*][]` with no such matching identifier,
the output is `[<em>Foo-bar</em>][*Foo-bar*]`
but ideally it would be `[*Foo-bar*][]` or at least `[<em>Foo-bar</em>][]`.

See https://github.com/mkdocstrings/autorefs/pull/5#discussion_r617119616

**Comment by pawamoy** [comment]
`*Foo-bar*` gets rendered to `<em>Foo-bar</em>`, and when comparing the title and id, autorefs finds that they are different so re-outputs the ref as `[title][id]` -> `[<em>Foo-bar</em>][*Foo-bar*]`.

Fixing this would be fixing an error case, not particularly worth it IMO. For this reason I'll just close this for now.
